# Generated by Django 5.0.5 on 2024-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_date_returned_borrowing_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
